[Overrides]
; Path to the 'Mods' folder.
ModsFolderPath =

[General]
; Production profile: no hot reload tooling.
EnableHotReloadSystem = 0
UseCache = 0
InvalidateCacheIfDLLDiffers = 1
SecondsToScanBeforeGivingUp = 30
bUseUObjectArrayCache = false

[EngineVersionOverride]
; KovaaK's telemetry reports Unreal 4.26.2, but UE4SS runtime has been
; more stable here with 4.27 override.
MajorVersion = 4
MinorVersion = 26

[ObjectDumper]
LoadAllAssetsBeforeDumpingObjects = 0

[CXXHeaderGenerator]
DumpOffsetsAndSizes = 0
KeepMemoryLayout = 0
LoadAllAssetsBeforeGeneratingCXXHeaders = 0

[UHTHeaderGenerator]
IgnoreAllCoreEngineModules = 1
IgnoreEngineAndCoreUObject = 1
MakeAllFunctionsBlueprintCallable = 0
MakeAllPropertyBlueprintsReadWrite = 0
MakeEnumClassesBlueprintType = 0
MakeAllConfigsEngineConfig = 0

[Debug]
ConsoleEnabled = 0
GuiConsoleEnabled = 0
GuiConsoleVisible = 0
GuiConsoleFontScaling = 1
GraphicsAPI = dx11
LiveViewObjectsPerGroup = 32768

[Threads]
SigScannerNumThreads = 1
SigScannerMultithreadingModuleSizeThreshold = 16777216

[Memory]
MaxMemoryUsageDuringAssetLoading = 85

[Hooks]
HookProcessInternal =0
HookProcessLocalScriptFunction =0
HookInitGameState =0
HookLoadMap =0
HookCallFunctionByNameWithArguments =0
HookBeginPlay  =0
HookEndPlay  =0
HookLocalPlayerExec =0
HookAActorTick =0
HookEngineTick =0
; Method for resolving GameEngine::Tick address
; Valid values (case-insensitive): Scan, VTable
; Scan: Use PatternSleuth AOB scan (fallback to VTable if scan fails)
; VTable: Use vtable lookup (fallback to Scan if vtable lookup fails)
; Default: Scan
EngineTickResolveMethod = Scan
HookGameViewportClientTick =0
HookUObjectProcessEvent =0
HookProcessConsoleExec =0
HookUStructLink =0
FExecVTableOffsetInLocalPlayer = 0x28

[CrashDump]
EnableDumping = 0
FullMemoryDump = 0

[ExperimentalFeatures]
GUIUFunctionCaller = 0
